### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Danieler** [bentorfs/angular-bootstrap-multiselect#32]
the npm package fails when i try to install it

**Comment by codemonkey00** [comment]
Did you ever figure this out?
I added it to my package.json and when i restore packages i get this error:

"c:\Program Files\nodejs\npm.CMD" install
> angular-bootstrap-multiselect@1.1.6 install C:\Projects\...\node_modules\angular-bootstrap-multiselect
> node node_modules/protractor/bin/webdriver-manager update
module.js:471
    throw err;
    ^
Error: Cannot find module 'C:\Projects\...\node_modules\angular-bootstrap-multiselect\node_modules\protractor\bin\webdriver-manager'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by ghost** [comment]
Me too! 


```
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! angular-bootstrap-multiselect@1.1.6 install: `node node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-bootstrap-multiselect@1.1.6 install script 'node node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-bootstrap-multiselect package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-bootstrap-multiselect
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-bootstrap-multiselect
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\wamp64\www\muscle\npm-debug.log
`
```

**Comment by zmbq** [comment]
Me three!

Attached is my npm-debug.log.

[npm-debug.zip](https://github.com/bentorfs/angular-bootstrap-multiselect/files/786948/npm-debug.zip)

**Comment by chinchaun** [comment]
Me four :(

**Comment by celina** [comment]
Also having this issue

**Comment by obondarets** [comment]
The same issue for me.

**Comment by nfalco79** [comment]
Here too, the install scripts broke in the `npm install` because you perform an update of webdriver-manager that is not a declared dependencies of your (and mine) project.
Adding the webdriver-manager as devDependencies of my project `npm install` fails again becuase the path on the install script are relative to the angular-bootstrap-multiselect folder so it try to update `${MY_PROJECT_PATH}\node_modules\angular-bootstrap-multiselect\node_modules\protractor\bin\webdriver-manager` and not the webdriver-manager in the expected node_modules folder ``${MY_PROJECT_PATH}\node_modules\protractor\bin\webdriver-manager`

Anyway I think that the install script is wrong, you named it different (like prj_setup) that is not triggered during other npm command.

**Comment by mishacucicea** [comment]
Do you think you could provide an update or resolution steps?
Thanks :)

**Comment by kevinboosten** [comment]
@mishacucicea @Danieler npm install should work again without issues, please verify by installing angular-bootstrap-multiselect via the master branch: 
`
"dependencies": {
   "angular-bootstrap-multiselect": "git+https://github.com/bentorfs/angular-bootstrap-multiselect.git#master"
  }`

**Comment by jfinckh** [comment]
@Boosten Verified, works perfect, thank you
